environment:
  matrix:
    # node.js
    - nodejs_version: "5"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

# Post-install test scripts.
test_script:
  # run tests
  - npm test

# Don't actually build.
build: off